title = "gitleaks custom config"

[allowlist]
description = "Skip test content"
paths = ['''leaks.*''', '''test''', '''.*/test/.*''', '''.*\/test\/.*''']

[[rules]]
id = "private-key"
description = "Detect private keys"
regex = '''-----BEGIN (:?[A-Z\-\s]*)PRIVATE KEY-----'''
tags = ["key"]
	
[[rules]]
id = "password-secret-apikey"
description = "Detect passwords/secrets/apikey"
regex = '''(?i)(password|pass|pwd|passwd|secret|apikey|api_key|api\-key)\s*(=|:)\s*.+'''
tags = ["secret"]

[[rules]]
id = "hash-with-identifier"
description = "Detect password hash"
regex = '''\$[a-zA-Z0-9]+\$[a-zA-Z0-9/\.\$=]{5,}'''
tags = ["hash"]

[[rules]]
id = "token-jwt"
description = "Detect JWT token"
regex = '''ey[A-Za-z0-9]{15,}\.[A-Za-z0-9]{15,}\.[A-Za-z0-9_-]*'''
tags = ["secret"]

[[rules]]
id = "private-ipv4-range10"
description = "Detect private IPv4 range 10"
regex = '''[\s"']{1}10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'''
tags = ["private-ipv4"]
	
[[rules]]
id = "private-ipv4-range172"
description = "Detect private IPv4 range 172.16"
regex = '''[\s"']{1}172\.16\.[0-9]{1,3}\.[0-9]{1,3}'''
tags = ["private-ipv4"]		

[[rules]]
id = "private-ipv4-range192"
description = "Detect private IPv4 range 192.168"
regex = '''[\s"']{1}192\.168\.[0-9]{1,3}\.[0-9]{1,3}'''
tags = ["private-ipv4"]
