title = "gitleaks custom config"

[allowlist]
description = "Skip test content"
paths = ['''test''', '''.*/test/.*''', '''.*\/test\/.*''']

[[rules]]
id = "private-key"
description = "Detect private keys"
regex = '''-----BEGIN (:?[A-Z\-\s]*)PRIVATE KEY-----'''
tags = ["private-keys"]
	
[[rules]]
id = "password-secret-apikey"
description = "Detect passwords/secrets/apikey"
regex = '''(?i)(password|pass|pwd|passwd|secret|apikey|api_key|api\-key)\s*(=|:)\s*.+'''
tags = ["passwords", "secrets", "apikey"]
	
[[rules]]
id = "hash-md5-sha1-sha256"
description = "Detect MD5/SHA1/SHA256 hashes"
regex = '''(?i)[0-9A-F]{32,64}'''
tags = ["md5", "sha1", "sha2"]	
	
[[rules]]
id = "hash-with-identifier"
description = "Detect password hashes"
regex = '''\$[a-zA-Z0-9]+\$[a-zA-Z0-9/\.\$=]{5,}'''
tags = ["password-hash"]
	
[[rules]]
id = "private-ipv4-range10"
description = "Detect private IPv4 range 10"
regex = '''10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'''
tags = ["private-ipv4"]
	
[[rules]]
id = "private-ipv4-range172"
description = "Detect private IPv4 range 172.16"
regex = '''172\.16\.[0-9]{1,3}\.[0-9]{1,3}'''
tags = ["private-ipv4"]		

[[rules]]
id = "private-ipv4-range192"
description = "Detect private IPv4 range 192.168"
regex = '''192\.168\.[0-9]{1,3}\.[0-9]{1,3}'''
tags = ["private-ipv4"]
