name: Update scripts index
on:
  push:
    branches: [ "master" ]
    paths:
      - "scripts/*.*"    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update the script index
        run: |
          chmod +x build_scripts_index.sh
          bash build_scripts_index.sh
      - name: Set up Git user
        run: git config --global user.email "gha@github.com"; git config --global user.name "GHActionBot"
      - name: Commit update
        run: git commit -am "Sync scripts index MD file"; git push
